### ISSUE TITLE
1.1 dettect old service worker, if found -> uninstall and install new one

### ISSUE THREAD

**Issue by yussan** [yussan/exploration-service-worker#2]

**Comment by ChrisMcNulty91** [comment]
I may be wrong here but from my understanding of services workers they will update at least every 24hrs if you are online. From the docs 

> The service worker is immediately downloaded when a user first accesses a service worker–controlled site/page. After that it is downloaded every 24 hours or so. It may be downloaded more frequently, but it must be downloaded every 24h to prevent bad scripts from being annoying for too long.

**Comment by yussan** [comment]
@ChrisMcNulty91 i have a case, in sample https://github.com/yussan/exploration-service-worker/tree/master/1.0.cache-static-files is using `service-worker.js` as configuration and loaded from main.js..

and then i delete service-worker.js , and change to sw.js , but browser still dettect service-worker.js, and return error 404, 

![deepinscreenshot_select-area_20171004180424](https://user-images.githubusercontent.com/4264672/31172643-9223c74e-a92e-11e7-8c90-dd32b06decc9.png)

question is, how to tell browser if i have new service worker file ?

**Comment by ChrisMcNulty91** [comment]
@yussan Ok, I can take a look at this and see if I can get it resolved

**Comment by ChrisMcNulty91** [comment]
@yussan I don't have as much free time as I expected. Someone else will have to jump on this issue sorry

**Comment by yussan** [comment]
@ChrisMcNulty91 it's ok
